import 'package:flutter/material.dart';
import '../../core/theme/app_theme.dart';
import '../../state/cart_controller.dart';
import '../../widgets/app_button.dart';
import 'order_complete_screen.dart';

class CheckoutScreen extends StatefulWidget { const CheckoutScreen({super.key}); @override State<CheckoutScreen> createState() => _CheckoutState(); }
class _CheckoutState extends State<CheckoutScreen> {
  int payment = 0;
  int shipping = 0;
  @override Widget build(BuildContext context) { final shippingCost = shipping == 0 ? 0.0 : 10.0; final total = cartController.subtotal + shippingCost; return Scaffold(appBar: AppBar(title: const Text('Check out'), leading: const BackButton()), body: SafeArea(child: SingleChildScrollView(padding: const EdgeInsets.fromLTRB(22, 8, 22, 28), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
    const Text('Shipping Address', style: TextStyle(fontSize: 18, fontWeight: FontWeight.w700)), const SizedBox(height: 12), Container(padding: const EdgeInsets.all(16), decoration: BoxDecoration(border: Border.all(color: AppColors.line), borderRadius: BorderRadius.circular(14)), child: const Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Icon(Icons.location_on_outlined), SizedBox(width: 10), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Al Iqra', style: TextStyle(fontWeight: FontWeight.w700)), SizedBox(height: 4), Text('123 Design Avenue, NSW City\nNY Australia', style: TextStyle(color: AppColors.muted, fontSize: 11, height: 1.4))])), Text('Edit', style: TextStyle(color: AppColors.coral))])), const SizedBox(height: 24),
    const Text('Shipping method', style: TextStyle(fontSize: 18, fontWeight: FontWeight.w700)), RadioListTile<int>(value: 0, groupValue: shipping, onChanged: (v) => setState(() => shipping = v!), title: const Text('Standard Delivery'), subtitle: const Text('3–5 business days • Free'), contentPadding: EdgeInsets.zero), RadioListTile<int>(value: 1, groupValue: shipping, onChanged: (v) => setState(() => shipping = v!), title: const Text('Express Delivery'), subtitle: const Text('1–2 business days • \$10'), contentPadding: EdgeInsets.zero),
    const SizedBox(height: 10), const Text('Payment Method', style: TextStyle(fontSize: 18, fontWeight: FontWeight.w700)), RadioListTile<int>(value: 0, groupValue: payment, onChanged: (v) => setState(() => payment = v!), title: const Text('VISA •••• 4242'), subtitle: const Text('Exp: 12/28'), contentPadding: EdgeInsets.zero), RadioListTile<int>(value: 1, groupValue: payment, onChanged: (v) => setState(() => payment = v!), title: const Text('Apple Pay'), contentPadding: EdgeInsets.zero),
    const SizedBox(height: 12), Container(padding: const EdgeInsets.all(18), decoration: BoxDecoration(color: AppColors.soft, borderRadius: BorderRadius.circular(14)), child: Column(children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [const Text('Product price'), Text('\$${cartController.subtotal.toStringAsFixed(2)}')]), const SizedBox(height: 8), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [const Text('Shipping'), Text('\$${shippingCost.toStringAsFixed(2)}')]), const Divider(height: 22), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [const Text('Total', style: TextStyle(fontWeight: FontWeight.w700)), Text('\$${total.toStringAsFixed(2)}', style: const TextStyle(fontWeight: FontWeight.w700))])])), const SizedBox(height: 20), AppButton(label: 'PLACE ORDER', onPressed: () => Navigator.pushReplacement(context, MaterialPageRoute(builder: (_) => OrderCompleteScreen(total: total))))
  ])))); }
}
